export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_SUCCESS = "ADD_SUCCESS";
export const ADD_FAIL = "ADD_FAIL";

export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";

export const JOIN_REQ_SUCCESS = "JOIN_REQ_SUCCESS";
export const JOIN_REQ_FAIL = "JOIN_REQ_FAIL";

export const GET_COLAB_REQ_SUCCESS = "GET_COLAB_REQ_SUCCESS";
export const GET_COLAB_REQ_FAIL = "GET_COLAB_REQ_FAIL";

export const RESPOND_C_REQ_SUCCESS = "RESPOND_C_REQ_SUCCESS";
export const RESPOND_C_REQ_FAIL = "RESPOND_C_REQ_FAIL";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
